### ISSUE TITLE
Ahmed's Road map

### ISSUE THREAD

**Issue by AhmedAlo1993** [Yusuf-zartit/Polyglot-Coders#11]
- [ ] Learn CSS and do some small projects
- [ ] EcmaScript ES6 (JS)
- [ ] REACT 
  - [ ] Components
  - [ ] Props
  - [ ] States
  - [ ] Lifecycle
  - [ ] Contacts App
  - [ ] Stillendirme Temelleri
  - [ ] Fetching
  - [ ] Routing
  - [ ] Formik ile Form Yönetimi
  - [ ] Memoization
  - [ ] Context API
  - [ ] Real Time Çalışan Uygulamalar Geliştirmek
  - [ ] Chat App
  - [ ] Localization
  - [ ] Testing
  - [ ] Publishing
  - [ ] Deploy
  - [ ] E-Commerce App
  - [ ] Coderbyte Challenge
