### ISSUE TITLE
Youssef's roadmap to master the spring boot framework.

### ISSUE THREAD

**Issue by Yusuf-zartit** [Yusuf-zartit/Polyglot-Coders#13]
## Java Startup
- [x] Java History
- [x] Why Java?
- [x] Java Runtime Environment (JRE)
- [x] Java Virtual Machine (JVM)
- [x] How Java works? From .java to .class

## Learn to master Java (Java SE / Java EE)
**Java Standard Edition (SE)**  
- [ ] Basic
  - [x] Comments
  - [x] Variables
  - [x] Data Types
    - [x] Primitive Data Types
    - [x] Non-Primitive (Wrapper Classes) Data Types
  - [x] Numbers
  - [x] Arrays
  - [x] If Statement
  - [x] Loops
  - [ ] Java Collections
    - [x] Lists
    - [x] Queues
    - [x] Maps
    - [x] Sets
    - [ ] Sorting Collections
    - [ ] Collection Class
  - [x] Foreach

- [x] Java OOP

- [ ] Advanced Level
  - [ ] Java Generics
  - [ ] Java Reflections
  - [ ] Annotations
  - [ ] Try-catch
  - [ ] Exceptions

**Java Enterprise Edition (EE)**  
- [ ] TODO: Add Java EE topics here
